name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check scaffold
        run: scripts/check-scaffold.sh
